### ISSUE TITLE
BetterToggle never setting the group

### ISSUE THREAD

**Issue by Eisman111** [CantyCanadian/CantysToolbox#1]
Hello there,

I noticed that in the BetterToggle you use the m_group to define group behavior but I can not find where you set it, and it was giving some weird behavior on my project. So what I did was to set it in the BetterToggleGroup during the Start cycle. Is it something that may need to be added or I was missing something?

p.s. thanks for your hardwork! Love this!

**Comment by CantyCanadian** [comment]
Wow, I never expected someone to stumble in my repo hahaha.

You are absolutely right, some code seems to be missing there. Your solution is the right way to go, I'll most likely fix it the moment I can.

However, you did make me notice that this repo is still public. I've actually cleaned a lot of code and added a lot of new stuff in it, it can be found on my profile split in three different repos (to make it easier to pick and choose features). BetterToggle is in CantysToolbox_Object, with the same bug still in there, make sure to have the Core repo also checked out in your project for all to work.

I'll reopen this ticket in the other repo. Thank you for noticing and using my work. It is super appreciated!

**Comment by Eisman111** [comment]
Thanks you for your hard work! I'll checkout the other projects then!
